#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

dotnet tool run husky run --name csharpier-format
dotnet tool run husky run --name csharpier-format
echo "Запуск модульных тестов..."
dotnet test "C:/Users/AAA/Desktop/InformationSystems/Practica1/Practica1.sln" --no-restore

# Проверяем код возврата последней команды.
# Если тесты не прошли (код не 0), Git отменит коммит.
if [ $? -ne 0 ]; then
  echo "Тесты не прошли. Коммит отменен."
  exit 1
fi
